# Generated by Django 4.2.2 on 2023-07-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='category_image/%Y/%m/%d', verbose_name='Category_icon'),
        ),
    ]
