# Generated by Django 4.2.2 on 2023-09-05 18:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='beginning_of_work_day_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='product',
            name='end_of_work_day_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='product',
            name='number_of_quests',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
