# Generated by Django 4.2.2 on 2023-09-06 04:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_beginning_of_work_day_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_day', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday '), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], default='MONDAY', max_length=9, verbose_name='name day')),
            ],
            options={
                'verbose_name': 'Work day',
                'verbose_name_plural': 'Work days',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='beginning_of_work_day_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='beginning of work time'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Products', to='store.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='end_of_work_day_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='end of work time'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=250, verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='work_days',
            field=models.ManyToManyField(related_name='Products', to='store.workdays'),
        ),
    ]
