# Generated by Django 4.2.2 on 2023-06-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateTimeField(default='2000-09-12', verbose_name='Birth date'),
        ),
    ]
