# Generated by Django 4.2.2 on 2023-06-30 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
    ]
